name: notices_app
description: "A test project for the Flutter Bloc library, using Dio for network requests"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  dio: ^5.3.3
  equatable: ^2.0.7
  intl: ^0.20.2
  go_router: ^15.1.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
